#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_common.sh
source "$SCRIPT_DIR/_common.sh"

need_bin jq

ensure_veil_dir
ensure_sdk

HAS_FORCE=false
for arg in "$@"; do [[ "$arg" == "--force" ]] && HAS_FORCE=true; done

if [[ -f "$VEIL_ENV" ]]; then
  echo "Veil env already exists: $VEIL_ENV" >&2
  echo "(delete it to regenerate, or pass --force)" >&2
  if [[ "$HAS_FORCE" != "true" ]]; then
    exit 0
  fi
  echo "Overwriting (--force)..." >&2
fi

VEIL_SIGNED_MESSAGE="Sign this message to create your Veil Wallet private key. This will be used to decrypt your balances. Ensure you are signing this message on the Veil Cash website."

# Try Bankr signature-based derivation first, fall back to random.
KP_JSON=""
try_bankr_signature() {
  local api_key api_url sign_resp sig

  # Need Bankr config for the signing API
  if ! [[ -f "$BANKR_CONFIG" ]]; then
    return 1
  fi
  api_key=$(jq -r '.apiKey // empty' "$BANKR_CONFIG")
  api_url=$(jq -r '.apiUrl // "https://api.bankr.bot"' "$BANKR_CONFIG")
  if [[ -z "$api_key" ]]; then
    return 1
  fi

  echo "Requesting wallet signature from Bankr..." >&2
  sign_resp=$(curl -sf -X POST "$api_url/agent/sign" \
    -H "X-API-Key: $api_key" \
    -H "Content-Type: application/json" \
    -d "$(jq -nc --arg msg "$VEIL_SIGNED_MESSAGE" '{signatureType: "personal_sign", message: $msg}')" 2>/dev/null) || return 1

  sig=$(echo "$sign_resp" | jq -r '.signature // empty' 2>/dev/null)
  if [[ -z "$sig" || "$sig" == "null" ]]; then
    echo "Bankr signing returned no signature, falling back to random keypair" >&2
    return 1
  fi

  echo "Deriving keypair from Bankr wallet signature..." >&2
  KP_JSON=$(veil_cli init --json --signature "$sig" "$@")
}

if ! try_bankr_signature "$@" 2>/dev/null; then
  echo "Using random keypair generation..." >&2
  KP_JSON=$(veil_cli init --json "$@")
fi

# Validate JSON
if ! echo "$KP_JSON" | jq empty 2>/dev/null; then
  echo "CLI did not return valid JSON:" >&2
  echo "$KP_JSON" >&2
  exit 1
fi

VEIL_KEY=$(echo "$KP_JSON" | jq -r '.veilPrivateKey // .veilKey')
DEPOSIT_KEY=$(echo "$KP_JSON" | jq -r '.depositKey')

if [[ -z "$VEIL_KEY" || "$VEIL_KEY" == "null" ]]; then
  echo "Failed to parse private key from CLI output" >&2
  echo "$KP_JSON" >&2
  exit 1
fi

if [[ -z "$DEPOSIT_KEY" || "$DEPOSIT_KEY" == "null" ]]; then
  echo "Failed to parse deposit key from CLI output" >&2
  echo "$KP_JSON" >&2
  exit 1
fi

cat > "$VEIL_ENV" << EOF
# Veil Cash Configuration
# Generated by: veil-init.sh
VEIL_KEY=$VEIL_KEY
DEPOSIT_KEY=$DEPOSIT_KEY
EOF

chmod 600 "$VEIL_ENV"
echo "Wrote: $VEIL_ENV" >&2
