"""Pydantic models for Polymarket API."""

from polymarket.models.auth import ApiCredentials, Credentials
from polymarket.models.bridge import (
    BridgeTransaction,
    DepositResponse,
    QuoteRequest,
    QuoteResponse,
    SupportedAsset,
    SupportedAssetsResponse,
    TransactionStatusResponse,
)
from polymarket.models.markets import (
    Comment,
    Event,
    Market,
    MarketToken,
    PublicProfile,
    SearchResults,
    Series,
    Tag,
    Team,
)
from polymarket.models.orderbook import (
    BalanceAllowance,
    OrderBookSummary,
    OrderLevel,
    PriceHistoryPoint,
    PriceHistoryResponse,
    SpreadInfo,
)
from polymarket.models.orders import (
    CancelResponse,
    OpenOrder,
    OrderRequest,
    OrderResponse,
    OrderSide,
    OrderType,
    SignatureType,
    SignedOrder,
    Trade,
)
from polymarket.models.positions import (
    Activity,
    ActivityType,
    BuilderLeaderboardEntry,
    ClosedPosition,
    Holder,
    LeaderboardEntry,
    LiveVolume,
    OpenInterestItem,
    Position,
)
from polymarket.models.websocket import (
    MarketEvent,
    UserEvent,
    WsAuth,
    WsBookMessage,
    WsLastTradePriceMessage,
    WsMakerOrder,
    WsOrderLevel,
    WsOrderMessage,
    WsPriceChange,
    WsPriceChangeMessage,
    WsSubscription,
    WsTradeMessage,
)

__all__ = [
    # Auth
    "ApiCredentials",
    "Credentials",
    # Orders
    "SignedOrder",
    "OrderRequest",
    "OrderResponse",
    "OpenOrder",
    "CancelResponse",
    "Trade",
    "OrderSide",
    "OrderType",
    "SignatureType",
    # Markets
    "Market",
    "MarketToken",
    "Event",
    "Series",
    "Tag",
    "Team",
    "Comment",
    "SearchResults",
    "PublicProfile",
    # Positions
    "Position",
    "ClosedPosition",
    "Activity",
    "ActivityType",
    "LeaderboardEntry",
    "BuilderLeaderboardEntry",
    "Holder",
    "LiveVolume",
    "OpenInterestItem",
    # Orderbook
    "OrderBookSummary",
    "OrderLevel",
    "SpreadInfo",
    "BalanceAllowance",
    "PriceHistoryResponse",
    "PriceHistoryPoint",
    # Bridge
    "SupportedAsset",
    "SupportedAssetsResponse",
    "DepositResponse",
    "QuoteRequest",
    "QuoteResponse",
    "BridgeTransaction",
    "TransactionStatusResponse",
    # WebSocket
    "WsSubscription",
    "WsAuth",
    "WsBookMessage",
    "WsOrderLevel",
    "WsPriceChangeMessage",
    "WsPriceChange",
    "WsLastTradePriceMessage",
    "WsTradeMessage",
    "WsMakerOrder",
    "WsOrderMessage",
    "MarketEvent",
    "UserEvent",
]
